---
- name: Wait Jenkins server
  wait_for:
    port: "{{ jenkins_port }}"
    delay: 10

# Create Jenkins CLI destination directory
- name: Create Jenkins CLI destination directory
  file:
    path: "{{ jenkins_dest }}"
    state: directory

# Get Jenkins CLI from localhost
- name: Get Jenkins CLI
  get_url:
    url: "http://localhost:{{ jenkins_port }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins.cli_dest }}"
    mode: 0440
  delay: 20
  retries: 5
  register: cli_downloaded
  until: not "failed" in cli_downloaded

# Get latest Jenkins update file
- name: Get Jenkins updates
  get_url:
    url: http://updates.jenkins-ci.org/update-center.json
    dest: "{{ jenkins.updates_dest }}"
    mode: 0440
    thirsty: yes
  register: jenkins_updates

# Jenkins Update-center
- name: Update-center Jenkins
  shell: "cat {{ jenkins.updates_dest }} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:{{ jenkins_port }}/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  notify: Restart Jenkins
