---
- name: Install/update plugins
  shell: "java -jar {{ jenkins.cli_dest }} -s http://localhost:{{ jenkins_port }} install-plugin {{ item }}"
  with_items: "{{ plugins }}"
  notify: Restart Jenkins
