---
git_repos:
  - branch: master
    repo: http://git.drupal.org/sandbox/coltrane/1921926.git
    name: DrupalSecure

  - branch: 7.x-1.x
    repo: https://github.com/klausi/drupalpractice.git
    name: DrupalPractice

  - branch: master
    repo: https://github.com/podarok/phpcs-security-audit.git
    name: Security

  - branch: master
    repo: https://github.com/podarok/Symfony2-coding-standard.git
    name: Symfony2

phpcs_standards:
  - vendor/drupal/coder/coder_sniffer/Drupal
  - vendor/podarok/DrupalSecure/DrupalSecure
  - vendor/podarok/Security/Security
  - vendor/podarok/DrupalPractice/DrupalPractice

npm_packages:
  - jshint

gem_packages:
  - scss-lint
